name: rtlive
channels:
  - conda-forge
dependencies:
  - black
  - fbprophet
  - ipython
  - iso3166
  - jupyterlab
  - libblas=*=*mkl
  - matplotlib
  - mkl-service
  - pandas
  - pip
  - pymc3 >=3.11
  - python-graphviz
  - requests
  - watermark
  - pip:
    - black_nbconvert
